---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  # TODO: enable
  enabled: False
platforms:
  - name: outreach.openmicroscopy.org
    image: centos/systemd
    image_version: latest
    command: /sbin/init
    privileged: true
    groups:
      - docker-hosts
      - omero-server
      - omero-web
      - monitored
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        molecule_test: True
      docker-hosts:
        omero_server_systemd_require_network: False
        # This should allow docker-in-docker to work
        docker_storage_driver: vfs
        # Latest version 17.12.1.ce-1.el7.centos has a bug that prevents
        # testing on travis: https://github.com/docker/for-linux/issues/219
        docker_version: 17.09.1.ce-1.el7.centos
        # firewalld isn't installed, don't attempt to disable
        iptables_raw_disable_firewalld: False
  # FIXME:
  # - Ansible 2.3 doesn't like "+t", remove this when we move to 2.4
  # - Use 5.4.6 to inlude pypi fix (only affects new installs):
  #   https://github.com/openmicroscopy/openmicroscopy/pull/5730
  # extra_vars: >
  #   omero_server_datadir_managedrepo_mode='u=rwX,g=srwX,o=rX'
  #   omero_server_release=5.4.6
  #   omero_web_release=5.4.6
  playbooks:
    prepare: prepare.yml
    converge: ../../site.yml
  lint:
    name: ansible-lint
scenario:
  name: omero-training-server
  test_sequence:
    # dependency must come first so that ansible-lint will see a custom module
    - dependency
    - lint
    - destroy
    - syntax
    - create
    - converge
    # FIXME: Some tasks are not idempotent
    #- idempotence
    - verify
    - destroy
  converge_sequence:
    - converge
verifier:
  name: testinfra
  lint:
    name: flake8
