sudo: required
language: python

services:
  - docker

install:
  - pip install ome-ansible-molecule-dependencies

script:
  # If PLAYBOOK is not defined assume that directory has a full
  # molecule.yml configuration file, otherwise use the default
  - >
      if [ -n "$PLAYBOOK" ]; then
          mv molecule-syntaxcheck.yml $DIRECTORY/molecule.yml;
          cd $DIRECTORY;
          mv $PLAYBOOK playbook.yml;
      else
          cd $DIRECTORY;
      fi
  - molecule test;
  # molecule-syntaxcheck.yml this doesn't run ansible-lint)
  - >
      if [ -n "$PLAYBOOK" ]; then
          ansible-lint playbook.yml;
      fi

env:
  - DIRECTORY="." PLAYBOOK=nightshade-web.yml
  - DIRECTORY="." PLAYBOOK=ome-demoserver.yml
  - DIRECTORY="." PLAYBOOK=ome-dundeeomero.yml
  - DIRECTORY=web-proxy PLAYBOOK=playbook.yml
  - DIRECTORY=www PLAYBOOK=""

matrix:
  allow_failures:
  - env: DIRECTORY="." PLAYBOOK=nightshade-web.yml
  - env: DIRECTORY="." PLAYBOOK=ome-dundeeomero.yml
  - env: DIRECTORY=web-proxy PLAYBOOK=playbook.yml
