---
sudo: required
language: python
python: 2.7

services:
  - docker

install:
  - pip install "ome-ansible-molecule<0.5"
  - pip install jmespath

script:
  - molecule test -s $SCENARIO

env:
  - SCENARIO=bootstrap
  - SCENARIO=k8s-postgres
  - SCENARIO=nightshade-webclients
  - SCENARIO=ome-demoserver
  - SCENARIO=ome-dundeeomero
  - SCENARIO=omero-training-server
  - SCENARIO=web-proxy
  - SCENARIO=www
