# Install OMERO.web with a public user on localhost

# To allow the OMERO.webapps to upgrade, pass `--extra-vars upgrade_webapps=True`
# to ansible-playbook on the command line.

- hosts: ns-webclients

  pre_tasks:

    # Set desired state of webapps (upgrade v.s. install/keep current version)
    - name: OMERO.web plugin upgrade | set default state "installed"
      set_fact:
        webapps_state: present
    - name: OMERO.web plugin upgrade | if --extra-vars upgrade_webapps == True, allow web plugin(s) to upgrade.
      set_fact:
        webapps_state: latest
      when: upgrade_webapps is defined and upgrade_webapps == "True"

  roles:

    # Root LV Size
    - role: openmicroscopy.lvm-partition
      tags: lvm
      lvm_lvname: "{{ provision_root_lvname }}"
      lvm_vgname: "{{ provision_root_vgname }}"
      lvm_lvmount: /
      lvm_lvsize: "{{ provision_rootsize }}"
      lvm_lvfilesystem: "{{ provision_root_filesystem }}"

    - role: openmicroscopy.ssl-certificate
      # Configuration for this role in `vars`

    - role: openmicroscopy.nginx

    # OMERO.web configuration in host_vars in different repository
    - role: openmicroscopy.omero-web
      omero_web_release: 5.4.9
      omero_web_systemd_limit_nofile: 16384

    # Now OME are using RHEL without Spacewalk, the current best-method of
    # checking `is server deployed in Dundee/SLS` is checking for the SLS nameservers.
    - role: openmicroscopy.system-monitor-agent
      when: "'10.1.255.216' in ansible_dns.nameservers"

  post_tasks:

    - name: Omero.web plugins | plugin install via pip & pypi
      become: yes
      pip:
        name:
        - "omero-figure{{ omero_figure_version_req | default('') }}"
        - "omero-webtagging-autotag"
        - "omero-webtagging-tagsearch"
        editable: False
        state: "{{ webapps_state }}"
        # variable comes from role openmicroscopy.omero-web
        virtualenv: "{{ omero_web_basedir }}/venv"
        virtualenv_site_packages: yes
      notify:
        - restart omero-web

    - name: Omero.web plugins | plugin install via pip & pypi
      become: yes
      pip:
        name:
        - "omero-fpbioimage"
        - "omero-iviewer"
        - "omero-parade"
        editable: False
        state: "{{ webapps_state }}"
        # variable comes from role openmicroscopy.omero-web
        virtualenv: "{{ omero_web_basedir }}/venv"
        virtualenv_site_packages: yes
      when: "'ns-web.openmicroscopy.org' in inventory_hostname"
      notify:
        - restart omero-web

    - name: Install open-vm-tools if system is a VMware vm
      become: yes
      yum:
        name: open-vm-tools
        state: present
      when: >
           ((ansible_virtualization_type is defined)
           and (ansible_virtualization_type == "VMware"))

    # (Total cores / 2), leaving some for WSGI
    # post 2.3 'dest' should be renamed 'path'
    - name: NGINX - Performance tuning - worker processes
      become: yes
      replace:
        dest: "/etc/nginx/nginx.conf"
        regexp: '^worker_processes\s+\d+;'
        replace: "worker_processes {{ ((ansible_processor_count * ansible_processor_cores) / 2) |round|int }};"

    # post 2.3 'dest' should be renamed 'path'
    # cf https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-configuration
    - name: NGINX - Performance tuning - worker connections
      become: yes
      replace:
        dest: "/etc/nginx/nginx.conf"
        regexp: 'worker_connections\s+\d+;'
        replace: "worker_connections 65000;"

    - name: NGINX - create nested includes directory
      become: yes
      file:
        path: /etc/nginx/conf.d-nested-includes
        state: directory

    - name: NGINX - omero-web.conf nested includes
      become: yes
      lineinfile:
        destfile: /etc/nginx/conf.d/omero-web.conf
        insertafter: 'server {'
        line: '    include /etc/nginx/conf.d-nested-includes/*.conf;'
      notify:
        - restart nginx

    - name: NGINX - SSL Configuration
      become: yes
      template:
        src: templates/nginx-confdnestedincludes-ssl-conf.j2
        dest: /etc/nginx/conf.d-nested-includes/ssl.conf
      notify:
        - restart nginx

    - name: NGINX - Custom Paper Redirect
      become: yes
      template:
        src: templates/nginx-confdnestedincludes-ns-pub-redirects-conf.j2
        dest: /etc/nginx/conf.d-nested-includes/ns-pub-redirects.conf
      notify:
        - restart nginx

    - name: Config for OMERO.web plugins
      become: yes
      template:
        src: templates/omero-web-config-for-webapps.j2
        dest: "{{ omero_web_basedir }}/config/omero-web-config-for-webapps.omero"
        owner: "root"
        group: "root"
        mode: "u=rw,go=r"
      when: "'ns-web.openmicroscopy.org' in inventory_hostname"
      notify:
        - restart omero-web

    - name: Config for OMERO.web plugins
      become: yes
      template:
        src: templates/omero-web-config-for-webapps_ns-web-pub.j2
        dest: "{{ omero_web_basedir }}/config/omero-web-config-for-webapps.omero"
        owner: "root"
        group: "root"
        mode: "u=rw,go=r"
      when: "'ns-web-pub.openmicroscopy.org' in inventory_hostname"
      notify:
        - restart omero-web

  vars:
    omero_web_config_set: "{{ omero_web_config_set_for_group | combine(omero_web_config_set_for_host) }}"

    nginx_version: 1.14.2

    # Disable SSL combined certificate and key
    ssl_certificate_combined_path: ''


- include: omero/omero-web-patch-settings.yml
