---

- name: openmicroscopy.certbot
  src: https://github.com/openmicroscopy/ansible-role-certbot/archive/0.1.0.tar.gz
  version: 0.1.0

- src: ome.cli_utils
  version: 1.1.0

- src: ome.deploy_archive
  version: 0.1.3

- src: openmicroscopy.docker
  version: 3.0.0

- src: ome.ice
  version: 3.0.0

- src: ome.java
  version: 2.0.3

- name: openmicroscopy.iptables-raw
  src: https://github.com/openmicroscopy/ansible-role-iptables-raw/archive/0.2.0.tar.gz
  version: 0.2.0

- src: openmicroscopy.lvm-partition
  version: 1.1.0

- name: openmicroscopy.network
  version: 1.1.2

- src: ome.nginx
  version: 1.1.1

- src: ome.nginx_proxy
  version: 1.12.0

- src: openmicroscopy.nfs-mount
  version: 1.0.0

- src: ome.omego
  version: 0.1.3

- src: ome.omero_common
  version: 0.1.0

- src: ome.basedeps
  version: 1.1.0

- src: ome.omero_prometheus_exporter
  version: 0.2.1

- src: ome.omero_python_deps
  version: 2.0.1

- src: ome.omero_server
  version: 2.0.6

- src: ome.omero_user
  version: 0.1.2

- name: ome.omero_web
  src: https://github.com/manics/ansible-role-omero-web
  version: restorecon

- src: ome.omero_web_django_prometheus
  version: 0.2.1

- src: openmicroscopy.lvm-partition
  version: 1.1.0

- src: openmicroscopy.postgresql
  version: 2.0.0

- src: ome.postgresql
  version: 3.2.0

- src: openmicroscopy.postgresql_backup
  version: 0.1.0

- name: openmicroscopy.prometheus
  src: openmicroscopy.ansible-role-prometheus
  version: 0.3.0

- name: openmicroscopy.prometheus-jmx
  src: openmicroscopy.ansible-role-prometheus-jmx
  version: 0.2.0

- name: openmicroscopy.prometheus-node
  src: openmicroscopy.ansible-role-prometheus-node
  version: 0.2.0

- name: openmicroscopy.prometheus-postgres
  src: openmicroscopy.ansible-role-prometheus-postgres
  version: 0.2.0

- name: ome.selinux_utils
  version: 1.0.3

- src: openmicroscopy.ssl-certificate
  version: 0.2.2

- src: openmicroscopy.sudoers
  version: 1.0.0

- src: openmicroscopy.system-monitor-agent
  version: 0.1.0

- src: openmicroscopy.upgrade-distpackages
  version: 1.1.0

- src: openmicroscopy.versioncontrol-utils
  version: 1.0.1

- name: idr.idr-jupyter
  src: idr.ansible-role-idr-jupyter
  version: 3.0.0
