---

- src: openmicroscopy.postgresql
  version: 2.0.0

- src: openmicroscopy.network
  version: 1.0.0

- name: openmicroscopy.omero-common
  version: 0.1.0

- name: openmicroscopy.omego
  version: 0.1.0

- name: openmicroscopy.omero-server
  version: 2.0.2

- name: openmicroscopy.omero-web
  version: 1.0.1

- name: openmicroscopy.omero-user
  version: 0.1.1

- name: openmicroscopy.lvm-partition
  version: 1.1.0

- name: openmicroscopy.system-monitor-agent
  version: 0.1.0

- src: openmicroscopy.sudoers
  version: 1.0.0
