---

- name: ome.certbot
  src: https://github.com/ome/ansible-role-certbot/archive/0.1.0.tar.gz
  version: 0.1.0

- src: ome.cli_utils
  version: 1.1.0

- src: ome.deploy_archive
  version: 0.1.3

- src: ome.docker
  version: 3.0.2

- src: ome.ice
  version: 3.0.0

- src: ome.java
  version: 2.0.3

- name: ome.iptables_raw
  version: 0.2.1

- src: ome.lvm_partition
  version: 1.1.1

- name: ome.network
  version: 1.1.3

- src: ome.nginx
  version: 1.1.1

- src: ome.nginx_proxy
  version: 1.12.0

- src: ome.nfs_mount
  version: 1.2.1

- src: ome.omego
  version: 0.1.3

- src: ome.omero_common
  version: 0.1.0

- src: ome.basedeps
  version: 1.1.0

- src: ome.omero_prometheus_exporter
  version: 0.2.1

- src: ome.omero_python_deps
  version: 2.0.1

- name: ome.omero_server_venv
  src: https://github.com/ome/ansible-role-omero-server/archive/83a6c6da31e351692dce9d12eb30d7e1bc49b874.tar.gz
  version: 83a6c6da31e351692dce9d12eb30d7e1bc49b874

- src: openmicroscopy.omero-user
  version: 0.1.1

- src: ome.omero_server
  version: 2.0.6

- name: openmicroscopy.omero-web
  src: https://github.com/ome/ansible-role-omero-web/archive/b5646f2f6a929afbe97e5a04bec6307cd3887d2d.tar.gz
  version: b5646f2f6a929afbe97e5a04bec6307cd3887d2d

- src: ome.omero_user
  version: 0.1.2

- src: ome.omero_web
  version: 2.0.3

- src: ome.omero_web_django_prometheus
  version: 0.2.1

- src: ome.postgresql
  version: 3.3.1

- src: ome.postgresql_backup
  version: 0.1.1

- src: ome.prometheus
  version: 0.3.1

- src: ome.prometheus_jmx
  version: 0.2.1

- src: ome.prometheus_node
  version: 0.2.1

- src: ome.prometheus_postgres
  version: 0.2.1

- name: ome.selinux_utils
  version: 1.0.3

- src: ome.ssl_certificate
  version: 0.3.2

- src: ome.sudoers
  version: 1.0.1

- src: ome.system_monitor_agent
  version: 0.1.1

- src: ome.upgrade_distpackages
  version: 1.1.1

- src: ome.versioncontrol_utils
  version: 1.0.2

- name: idr.idr-jupyter
  src: idr.ansible-role-idr-jupyter
  version: 3.0.0
