---
# ansible-playbook -i <INVENTORY-DIR>/prod-hosts site.yml

# For new hosts you may also need to run the bootstrap playbook to setup
# networking and initial partitions:
#- include: bootstrap/playbook.yml

- include: nightshade-webclients.yml
- include: ome-demoserver.yml
- include: ome-dundeeomero.yml
- include: omero/training-server/playbook.yml

- include: omero/omero-firewall.yml
- include: omero/omero-monitoring-agents.yml

- include: jupyterhub/playbook.yml
