---
# ansible-playbook server-state-playbooks/site.yml --list-hosts
# Optionally passing an inventory: -i ../ansible/inventory/prod-hosts
- include: nightshade-webclients.yml
- include: ome-demoserver.yml
- include: ome-dundeeomero.yml
- include: omero/training-server/playbook.yml

- include: omero/omero-firewall.yml
- include: omero/omero-monitoring-agents.yml
