# Setup www

# Use fake certificates for testing
- hosts: www
  roles:
  - role: openmicroscopy.nginx-ssl-selfsigned
    nginx_ssl_certificate: "{{ nginx_ssl_files_path }}/{{ nginx_ssl_cert_filename }}"
    nginx_ssl_certificate_key: "{{ nginx_ssl_files_path }}/{{ nginx_ssl_key_filename }}"

- include: www-deploy.yml
# www-deploy.yml includes www-jekyll.yml
