---

- name: openmicroscopy.nginx-proxy
  version: 1.5.2

- name: openmicroscopy.nginx-ssl-selfsigned

- src: openmicroscopy.network
  version: 1.0.0

# dependancy of nginx_proxy
- name: openmicroscopy.selinux-utils
  version: 1.0.3

- src: openmicroscopy.jekyll-build
  version: 1.2.1

- name: openmicroscopy.system-monitor-agent
  src: https://github.com/openmicroscopy/ansible-role-system-monitor-agent.git

- src: openmicroscopy.lvm-partition
  version: 1.1.0
