# Update the static website

- hosts: www

  roles:
  - role: openmicroscopy.deploy_archive
    become: yes
    tags: jekyll

  vars:
    website_version: "2019.01.24"
    website_name: www.openmicroscopy.org
    deploy_archive_dest_dir: /var/www/{{ website_name }}/{{ website_version }}
    deploy_archive_src_url: https://github.com/openmicroscopy/{{ website_name }}/releases/download/{{ website_version }}/{{ website_name }}.tar.gz
    # Optional checksum. It should be safe to omit as long as you never
    # overwrite an existing archive. This should not be a problem when using
    # versioned directories.
    deploy_archive_sha256: cb0b8ee371a1e5023e82888f2fcea6723032522d8c8c684f50008b0812ff6e97
    deploy_archive_symlink: /var/www/{{ website_name }}/html
