# Update the static website

- hosts: www

  roles:
  - role: ome.deploy_archive
    become: yes
    deploy_archive_dest_dir: /var/www/{{ website_name }}/{{ website_version }}
    deploy_archive_src_url: https://github.com/ome/{{ website_name }}/releases/download/{{ website_version }}/{{ website_name }}.tar.gz
    # Optional checksum. It should be safe to omit as long as you never
    # overwrite an existing archive. This should not be a problem when using
    # versioned directories.
    deploy_archive_sha256: 9c9ab577f82a87c1416d9d192982b499367460475473d29c70898b823b006005
    deploy_archive_symlink: /var/www/{{ website_name }}/html
    tags: jekyll

  - role: ome.deploy_archive
    become: yes
    deploy_archive_dest_dir: /var/www
    deploy_archive_src_url: https://downloads.openmicroscopy.org/web-archive/phpbbforum-20190718.tar.gz
    deploy_archive_sha256: e9d7a7eefbacf42ddbdf92b201584913cb6d94ec331750f811232b2e91aa5b40

  vars:
    website_version: "2019.07.18"
    website_name: www.openmicroscopy.org
