# Install NGINX

- hosts: www

  pre_tasks:

    - name: NGINX - SSL File Deployment
      become: yes
      copy:
        dest="{{ item.key }}"
        content="{{ item.value.content }}"
        owner="{{ item.value.owner }}"
        group="{{ item.value.group }}"
        mode="{{ item.value.mode }}"
      with_dict: "{{ nginx_ssl_cert_files }}"
      no_log: true

  roles:

    - role: openmicroscopy.nginx_proxy
      tags: nginxconf
      nginx_proxy_worker_processes: "{{ ((ansible_processor_count * ansible_processor_cores) / 2) |round|int }}"
      nginx_proxy_ssl: True
      nginx_proxy_ssl_certificate: "{{ nginx_ssl_files_path }}/{{ nginx_ssl_cert_filename }}"
      nginx_proxy_ssl_certificate_key: "{{ nginx_ssl_files_path }}/{{ nginx_ssl_key_filename }}"
      nginx_proxy_http2: True
      nginx_proxy_force_ssl: False
      nginx_proxy_404: "/404.html"
      nginx_proxy_conf_http:
        - "client_max_body_size 2g"

  tasks:

    - name: NGINX - Performance tuning - worker processes
      tags: nginxconf
      become: yes
      replace:
        path: "/etc/nginx/nginx.conf"
        regexp: '^worker_processes\s+\d+;'
        replace: "worker_processes {{ ((ansible_processor_count * ansible_processor_cores) / 2) |round|int }};"

    # cf https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-configuration
    - name: NGINX - Performance tuning - worker connections
      tags: nginxconf
      become: yes
      replace:
        path: "/etc/nginx/nginx.conf"
        regexp: 'worker_connections\s+\d+;'
        replace: "worker_connections 65000;"

  vars:

    # Vars for role openmicroscopy.nginx_proxy
    nginx_proxy_backends:
      # Proxy for phpBB forums
      - location: /community
        server: https://www-legacy.openmicroscopy.org/community
      # Proxy for QA application
      - location: /qa2
        server: https://www-legacy.openmicroscopy.org/qa2
      - location: /static
        server: https://www-legacy.openmicroscopy.org
      # Proxy locations for OME Data Model schemas
      - location: /Schemas
        server: https://www-legacy.openmicroscopy.org/Schemas
      - location: /XMLschemas
        server: https://www-legacy.openmicroscopy.org/XMLschemas
      - location: /schema_doc
        server: https://www-legacy.openmicroscopy.org

    nginx_proxy_redirect_map_locations:
    # TODO: change to 301 when we're happy
    - location: "~ ^/(site)($|/)"
      code: 302
    - location: "~ ^/(omero-blog)($|/)"
      code: 302
    - location: "~ ^/(info)($|/)"
      code: 302

    nginx_proxy_redirect_map:
    # by default redirect to the 404 page
    - match: default
      dest: /404.html
    - match: "~/info/?$"
      dest: /
    - match: "~/info/vulnerabilities/?$"
      dest: /security/advisories/
    - match: "~/info/vulnerabilities/(?<link>.*[^/])/?$"
      dest: /security/advisories/$link/
    - match: "~/info/(?<link>.*)$"
      dest: https://www-legacy.openmicroscopy.org/info/$link
    - match: "~/omero-blog.*"
      dest: http://blog.openmicroscopy.org
    - match: "~/site/?$"
      dest: /
    - match: "~/site/news/?$"
      dest: /announcements

    # about
    - match: "~/site/about/?$"
      dest: /about
    - match: "~/site/about/who-ome"
      dest: /teams
    - match: "~/site/about/licensing-attribution/?$"
      dest: /licensing
    - match: "~/site/about/ome-contributors/?$"
      dest: /contributors
    - match: "~/site/about/partners/?$"
      dest: /commercial-partners
    - match: "~/site/about/development-teams/?$"
      dest: /teams
    - match: "~/site/about/development-teams/glencoe-software"
      dest: https://www.glencoesoftware.com/team.html
    - match: "~/site/about/publications"
      dest: /citing-ome
    - match: "~/site/about/(?<link>.*)$"
      dest: /about

    # products
    - match: "~/site/products/?$"
      dest: /products
    - match: "~/site/products/omero/?$"
      dest: /omero
    - match: "~/site/products/omero/downloads/?$"
      dest: /omero/downloads/
    - match: "~/site/products/omero/feature-list/?$"
      dest: /omero/new
    - match: "~/site/products/omero/big-images-support/?$"
      dest: /omero/view/
    - match: "~/site/products/omero/secvuln/?$"
      dest: /security/advisories/
    - match: "~/site/products/omero/secvuln/(?<link>.*[^/])/?$"
      dest: /security/advisories/$link/
    - match: "~/site/products/bio-formats/?$"
      dest: /bio-formats
    - match: "~/site/products/bio-formats/downloads/?$"
      dest: /bio-formats/downloads/
    - match: "~/site/products/ome-files-cpp/?$"
      dest: /ome-files
    - match: "~/site/products/(?<link>.*)$"
      dest: https://www-legacy.openmicroscopy.org/site/products/$link

    # community
    - match: "~/site/community/?$"
      dest: /support
    - match: "~/site/community/mailing-lists/?$"
      dest: /support
    - match: "~/site/community/jobs/?$"
      dest: /careers
    - match: "~/site/community/(?<link>.*)$"
      dest: https://www-legacy.openmicroscopy.org/site/community/$link

    # support
    - match: "~/site/support/?$"
      dest: /docs
    - match: "~/site/support/(?<link>.*)$"
      dest: https://www-legacy.openmicroscopy.org/site/support/$link

    nginx_proxy_direct_locations:
    - location: "/"
      root: "/var/www/{{ website_name }}/html"
      index: index.html


- include: www-jekyll.yml
