# Update the static website

- hosts: www

  roles:
  - role: openmicroscopy.deploy_archive
    become: yes
    tags: jekyll

  vars:
    website_version: "2019.04.01"
    website_name: www.openmicroscopy.org
    deploy_archive_dest_dir: /var/www/{{ website_name }}/{{ website_version }}
    deploy_archive_src_url: https://github.com/openmicroscopy/{{ website_name }}/releases/download/{{ website_version }}/{{ website_name }}.tar.gz
    # Optional checksum. It should be safe to omit as long as you never
    # overwrite an existing archive. This should not be a problem when using
    # versioned directories.
    deploy_archive_sha256: 23c6423304868edab1379d5fe5d279eeb9f7ecc69c7444034ec4c0da42f087ab
    deploy_archive_symlink: /var/www/{{ website_name }}/html
