# Update the static website

- hosts: www

  # TODO: Remove these pre-tasks after the new archive is deployed to
  # production for the first time
  pre_tasks:

  - name: Check for old deployment directory
    stat:
      path: "{{ deploy_archive_symlink }}"
    register: _archive_symlink_st

  - name: Rename old deployment directory if present
    become: yes
    command: mv "{{ deploy_archive_symlink }}" "{{ deploy_archive_symlink }}.old-jekyll-deploy"
    when: _archive_symlink_st.stat.exists and _archive_symlink_st.stat.isdir

  roles:
  - role: openmicroscopy.deploy-archive
    become: yes
    tags: jekyll

  vars:
    website_version: 20180711
    deploy_archive_dest_dir: /var/www/{{ website_name }}/{{ website_version }}
    deploy_archive_src_url: https://github.com/sbesson/www.openmicroscopy.org/releases/download/{{ website_version }}/wwww.openmicroscopy.org.tar.gz
    deploy_archive_sha256: 5d8fe25d0ed104e9120f054da9488080de297872a7a01b2278f135ae8914e8fc
    deploy_archive_symlink: /var/www/{{ website_name }}/html
