# Install NGINX

- hosts: www

  roles:
    - role: openmicroscopy.ssl-certificate
    - role: openmicroscopy.nginx-proxy
      tags: nginxconf

  vars:
    ssl_certificate_path: /etc/nginx/ssl/star_openmicroscopy_org-20161006.crt+bundle
    ssl_certificate_key_path: /etc/nginx/ssl/star_openmicroscopy_org-20141020.key
    # Vars for role openmicroscopy.nginx-proxy
    nginx_proxy_worker_processes: "{{ ((ansible_processor_count * ansible_processor_cores) / 2) |round|int }}"
    nginx_proxy_worker_connections: 65000
    nginx_proxy_ssl: True
    nginx_proxy_ssl_certificate: "{{ ssl_certificate_path }}"
    nginx_proxy_ssl_certificate_key: "{{ ssl_certificate_key_path }}"
    nginx_proxy_http2: True
    nginx_proxy_force_ssl: False
    nginx_proxy_404: "/404.html"
    nginx_proxy_conf_http:
      - "client_max_body_size 2g"
    nginx_proxy_backends:
      # Proxy for phpBB forums
      - location: /community
        server: https://www-legacy.openmicroscopy.org/community
      # Proxy for QA application
      - location: /qa2
        server: https://www-legacy.openmicroscopy.org/qa2
      - location: /static
        server: https://www-legacy.openmicroscopy.org
      # Proxy locations for OME Data Model schemas
      - location: /Schemas
        server: https://www-legacy.openmicroscopy.org/Schemas
      - location: /XMLschemas
        server: https://www-legacy.openmicroscopy.org/XMLschemas
      - location: /schema_doc
        server: https://www-legacy.openmicroscopy.org

    nginx_proxy_redirect_map_locations:
    # TODO: change to 301 when we're happy
    - location: "~ ^/(site)($|/)"
      code: 302
    - location: "~ ^/(omero-blog)($|/)"
      code: 302
    - location: "~ ^/(info)($|/)"
      code: 302

    nginx_proxy_redirect_map:
    # by default redirect to the 404 page
    - match: default
      dest: /404.html
    - match: "~/info/?$"
      dest: /
    - match: "~/info/vulnerabilities/?$"
      dest: /security/advisories/
    - match: "~/info/vulnerabilities/(?<link>.*[^/])/?$"
      dest: /security/advisories/$link/
    - match: "~/info/(?<link>.*)$"
      dest: https://www-legacy.openmicroscopy.org/info/$link
    - match: "~/omero-blog.*"
      dest: http://blog.openmicroscopy.org
    - match: "~/site/?$"
      dest: /
    - match: "~/site/news/?$"
      dest: /announcements

    # about
    - match: "~/site/about/?$"
      dest: /about
    - match: "~/site/about/who-ome"
      dest: /teams
    - match: "~/site/about/licensing-attribution/?$"
      dest: /licensing
    - match: "~/site/about/ome-contributors/?$"
      dest: /contributors
    - match: "~/site/about/partners/?$"
      dest: /commercial-partners
    - match: "~/site/about/development-teams/?$"
      dest: /teams
    - match: "~/site/about/development-teams/glencoe-software"
      dest: https://www.glencoesoftware.com/team.html
    - match: "~/site/about/publications"
      dest: /citing-ome
    - match: "~/site/about/what-omero/overview"
      dest: /omero
    - match: "~/site/about/(?<link>.*)$"
      dest: /about

    # products
    - match: "~/site/products/?$"
      dest: /products
    - match: "~/site/products/omero/?$"
      dest: /omero
    - match: "~/site/products/omero/downloads/?$"
      dest: /omero/downloads/
    - match: "~/site/products/omero/feature-list/?$"
      dest: /omero/features/
    - match: "~/site/products/omero/big-images-support/?$"
      dest: /omero/view/
    - match: "~/site/products/omero/secvuln/?$"
      dest: /security/advisories/
    - match: "~/site/products/omero/secvuln/(?<link>.*[^/])/?$"
      dest: /security/advisories/$link/
    - match: "~/site/products/bio-formats/?$"
      dest: /bio-formats
    - match: "~/site/products/bio-formats/downloads/?$"
      dest: /bio-formats/downloads/
    - match: "~/site/products/ome-files-cpp/?$"
      dest: /ome-files
    - match: "~/site/products/(?<link>.*)$"
      dest: https://www-legacy.openmicroscopy.org/site/products/$link

    # community
    - match: "~/site/community/?$"
      dest: /support
    - match: "~/site/community/mailing-lists/?$"
      dest: /support
    - match: "~/site/community/minutes/meetings/12th-annual-users-meeting-2017"
      dest: /events/12th-annual-users-meeting-2017.html
    - match: "~/site/community/minutes/meetings/11th-annual-users-meeting-2016"
      dest: /events/11th-annual-users-meeting-2016.html
    - match: "~/site/community/minutes/meetings/10th-annual-users-meeting-june-2015"
      dest: /events/10th-annual-users-meeting-june-2015.html
    - match: "~/site/community/minutes/meetings/9th-annual-users-meeting-june-2014"
      dest: /events/9th-annual-users-meeting-june-2014.html
    - match: "~/site/community/jobs/?$"
      dest: /careers
    - match: "~/site/community/scripts/?$"
      dest: https://docs.openmicroscopy.org/latest/omero/developers/scripts/index.html
    - match: "~/site/community/(?<link>.*)$"
      dest: https://www-legacy.openmicroscopy.org/site/community/$link

    # support
    - match: "~/site/support/?$"
      dest: /docs
    - match: "~/site/support/ome-artwork(/.*)?$"
      dest: /artwork
    - match: "~/site/support/(?<link>.*)$"
      dest: https://www-legacy.openmicroscopy.org/site/support/$link

    nginx_proxy_direct_locations:
    - location: "/"
      root: "/var/www/{{ website_name }}/html"
      index: index.html


- include: www-jekyll.yml
