# Update the static website

- hosts: www

  roles:
  - role: openmicroscopy.deploy_archive
    become: yes
    tags: jekyll

  vars:
    website_version: "2019.07.10"
    website_name: www.openmicroscopy.org
    deploy_archive_dest_dir: /var/www/{{ website_name }}/{{ website_version }}
    deploy_archive_src_url: https://github.com/ome/{{ website_name }}/releases/download/{{ website_version }}/{{ website_name }}.tar.gz
    # Optional checksum. It should be safe to omit as long as you never
    # overwrite an existing archive. This should not be a problem when using
    # versioned directories.
    deploy_archive_sha256: e404d64541236e00e5d3b451beaf286bc0e8ca0934df0ae3f48a4f5fd3308407
    deploy_archive_symlink: /var/www/{{ website_name }}/html
