# Update the static website

- hosts: www

  roles:
  - role: openmicroscopy.deploy_archive
    become: yes
    tags: jekyll

  vars:
    website_version: "2019.06.19"
    website_name: www.openmicroscopy.org
    deploy_archive_dest_dir: /var/www/{{ website_name }}/{{ website_version }}
    deploy_archive_src_url: https://github.com/ome/{{ website_name }}/releases/download/{{ website_version }}/{{ website_name }}.tar.gz
    # Optional checksum. It should be safe to omit as long as you never
    # overwrite an existing archive. This should not be a problem when using
    # versioned directories.
    deploy_archive_sha256: eeef01aef2fd36241155e9e6edbfc0bbeaf1a160a5854c827baa3ac01447cbc5
    deploy_archive_symlink: /var/www/{{ website_name }}/html
